name: Build Docker
on: [push]
jobs:
    build_hello_world:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
          with:
            ref: refs/heads/master
        - uses: actions/setup-node@v1
          with:
            node-version: 12.x 
        - name: Npm Test 
          run: echo "hello world"

